set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/briandeniz/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/briandeniz/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/ZeroToFiveCounter"
set ::env(//) "Technology-Specific Configs"
set ::env(DESIGN_NAME) "ZeroToFiveCounter"
set ::env(VERILOG_FILES) "/openlane/designs/ZeroToFiveCounter/src/ZeroToFiveCounter.v /openlane/designs/ZeroToFiveCounter/src/SevenSegmentDecoder.v"
set ::env(CLOCK_PERIOD) "10"
set ::env(CLOCK_PORT) "clk"
set ::env(PNR_SDC_FILE) "/openlane/designs/ZeroToFiveCounter/src/ZeroToFiveCounter.sdc"
set ::env(SIGNOFF_SDC_FILE) "/openlane/designs/ZeroToFiveCounter/src/ZeroToFiveCounter.sdc"
set ::env(PL_RANDOM_GLB_PLACEMENT) "1"
set ::env(FP_SIZING) "absolute"
set ::env(DIE_AREA) "0 0 210 360"
set ::env(PL_TARGET_DENSITY) "0.6"
set ::env(FP_PDN_AUTO_ADJUST) "0"
set ::env(FP_PDN_VPITCH) "25"
set ::env(FP_PDN_HPITCH) "25"
set ::env(FP_PDN_VOFFSET) "5"
set ::env(FP_PDN_HOFFSET) "5"
set ::env(DIODE_INSERTION_STRATEGY) "3"
set ::env(FP_PIN_ORDER_CFG) "/openlane/designs/ZeroToFiveCounter/pin_order.cfg"
set ::env(FP_CORE_UTIL) "30"
